spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring-security?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
    maximumPoolSize: 20